### PR TITLE
fix-password-validation-not-working

### PR DESCRIPTION
**Pull request by ashgansh**
### TL;DR

Updated the password validation logic in the PasswordCard component to only show the password mismatch message when both passwords are filled and to simplify the validation logic.

### What changed?

- Show password mismatch message only when both passwords are filled.
- Simplified password match condition.
- Removed unnecessary length checks for password and confirmPassword fields.

### How to test?

1. Go to the Join secure page.
2. Fill in the password and confirmPassword fields with non-matching passwords.
3. Verify that the password mismatch message only shows up when both fields are filled.

### Why make this change?

Improving user experience by providing clearer validation messages and simplifying the component's logic.

---

## What does this PR do?

Fixes # (issue)

_If there is not an issue for this, please create one first. This is used to tracking purposes and also helps use understand why this PR exists_

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Required

- [ ] Read [Contributing Guide](https://github.com/un/inbox/blob/main/CONTRIBUTING.md)
- [ ] Self-reviewed my own code
- [ ] Tested my code in a local environment
- [ ] Commented on my code in hard-to-understand areas
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the UnInbox Docs if changes were necessary

## Current Change
<div class='graphite__hidden'>
          <div>🎥 Video uploaded on Graphite:</div>
            <a href="https://app.graphite.dev/media/video/QhCUvoKQOmBB6W2whC7Z/8d5b2076-712b-41b3-b0eb-e31ce7868423.mov">
              
            </a>
          </div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/QhCUvoKQOmBB6W2whC7Z/8d5b2076-712b-41b3-b0eb-e31ce7868423.mov">Screen Recording 2024-07-23 at 15.25.42.mov</video>

## Past Behavior
Nothing would happen until a user entered at least 8 chars.

<div class='graphite__hidden'>
          <div>🎥 Video uploaded on Graphite:</div>
            <a href="https://app.graphite.dev/media/video/QhCUvoKQOmBB6W2whC7Z/cca615ba-2dc7-4ecd-a5e8-6f2674cd953e.mov">
              
            </a>
          </div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/QhCUvoKQOmBB6W2whC7Z/cca615ba-2dc7-4ecd-a5e8-6f2674cd953e.mov">Screen Recording 2024-07-23 at 15.33.38.mov</video>

### CODE REVIEW

**Comment by ashgansh** [comment]
* **#595** <a href="https://app.graphite.dev/github/pr/un/inbox/595?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ashgansh and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by McPizza0 — CHANGES_REQUESTED** [review]
@ashgansh I think that the "too weak" error message should be shown as soon as the first validation comes back (14 second timestamp in first video)

this would let the user make a stronger password BEFORE they start the confirmation step

also, i think previously the color of the strength bars were dynamic
red for weak
amber for medium
green for strong

maybe im imagining it @BlankParticle ?

**Comment by BlankParticle** [comment]
Yeah the remote validation doesn't occur until atleast 8 letters are there, also about the strength meter colors, it doesnt play well with when using the same component for both strength and confirm password.

**Comment by ashgansh** [comment]
> @ashgansh I think that the "too weak" error message should be shown as soon as the first validation comes back (14 second timestamp in first video)
> 
> this would let the user make a stronger password BEFORE they start the confirmation step
> 
> also, i think previously the color of the strength bars were dynamic red for weak amber for medium green for strong
> 
> maybe im imagining it @BlankParticle ?


when user under 8 chars returning an error
when password over 8 return the  strength in strength bar

note:
removed the color part of the bar for the moment + giving proper user follow up

**Review by McPizza0 — APPROVED** [review]
🫡

**Pull request merged**
