### PR TITLE
feat: web app env is now type safe and auto prefixed

### PR DESCRIPTION
**Pull request by BlankParticle**
## What does this PR do?

Web app env is now typesafe and we dont need to define `NEXT_PUBLIC_` prefixed env anymore. We can expose selected env variables.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Required

- [ ] Read [Contributing Guide](https://github.com/un/inbox/blob/main/CONTRIBUTING.md)
- [ ] Self-reviewed my own code
- [ ] Tested my code in a local environment
- [ ] Commented on my code in hard-to-understand areas
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the UnInbox Docs if changes were necessary

### CODE REVIEW

**Comment by BlankParticle** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/un/inbox/558?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#558** <a href="https://app.graphite.dev/github/pr/un/inbox/558?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#557** <a href="https://app.graphite.dev/github/pr/un/inbox/557?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#554** <a href="https://app.graphite.dev/github/pr/un/inbox/554?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#556](https://github.com/un/inbox/pull/556) <a href="https://app.graphite.dev/github/pr/un/inbox/556?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @BlankParticle and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by McPizza0 — CHANGES_REQUESTED** [review]
does not feel right
i think theres big risk of stuff being exposed
needs very very deep review and testing

**Comment by BlankParticle** [comment]
> does not feel right i think theres big risk of stuff being exposed needs very very deep review and testing

I did my analysis on this, upon building the app none of the env variables are hardcoded.
Only variables listed in the public list is hard-coded into the html shell that is sent to browser.

Any traces of process.env is treeshaken out.
I have checked the compiled output that is shipped to the end user.

**Review by McPizza0 — APPROVED** [review]

**Comment by BlankParticle** [comment]
### Merge activity

* **Jul 15, 5:18 AM EDT**: @BlankParticle merged this pull request with [Graphite](https://app.graphite.dev/github/pr/un/inbox/558).

**Pull request merged**
