### PR TITLE
chore: setup formatting with git-hooks

### PR DESCRIPTION
**Pull request by BlankParticle**
## What does this PR do?
Setup auto formatting before commits using git hooks (husky, lint-staged) to avoid CI failing due to a silly formatting issue, test/lint would not be added in git hooks as they take significant time to execute, so they would be run on CI only.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Required

- [ ] Read [Contributing Guide](https://github.com/un/inbox/blob/main/CONTRIBUTING.md)
- [ ] Self-reviewed my own code
- [ ] Tested my code in a local environment
- [ ] Commented on my code in hard-to-understand areas
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the UnInbox Docs if changes were necessary

### CODE REVIEW

**Comment by BlankParticle** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/un/inbox/184?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#184** <a href="https://app.graphite.dev/github/pr/un/inbox/184?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#183** <a href="https://app.graphite.dev/github/pr/un/inbox/183?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @BlankParticle and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by BlankParticle** [comment]
The PR size looks big due to `pnpm-lock.yaml` not being formatted, which we should not do at the first place. It is now excluded from being formatted in future

**Comment by McPizza0** [comment]
do we also wanna run checks, not just format?

**Comment by BlankParticle** [comment]
> do we also wanna run checks, not just format?

Running checks on local machine takes significant amount of time on local machine and it would prevent you from pushing broken code in draft prs.

**Review by McPizza0 — APPROVED** [review]

**Comment by BlankParticle** [comment]
### Merge activity

* **Mar 30, 9:01 AM EDT**: @BlankParticle merged this pull request with [Graphite](https://app.graphite.dev/github/pr/un/inbox/184).

**Pull request merged**
