### PR TITLE
feat:(web-app) - Added User Security Page

### LINKED ISSUE #80: feat(web-app): User Security Page
Once #79 merges, we need to add a new security settings page so users can manage their own security

they should be able to:
- verify their recovery email address (if not verified)
- change their recovery email address
- change their password (if one is set, or set one up if not)
- switch on/off password auth if they have passkeys enabled
- setup TOTP 2FA (separate issue)
- manage their passkeys (add, remove)
- manage their user sessions (destroy session, log out of all devices)

### PR DESCRIPTION
**Pull request by skushagra9**
## What does this PR do?

Fixes #80 

*If there is not an issue for this, please create one first. This is used to tracking purposes and also helps use understand why this PR exists*

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Required
- [x] Read [Contributing Guide](./CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [x] Tested my code in a local environment
- [x] Commented on my code in hard-to-understand areas
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the UnInbox Docs if changes were necessary

image

### CODE REVIEW

**Comment by skushagra9** [comment]
@McPizza0 , please let me know if any design or architectural changes are required for now

**Comment by McPizza0** [comment]
@skushagra9 it looks a little bit disorganized, maybe we need a designer to do some designs first

**Comment by skushagra9** [comment]
> @skushagra9 it looks a little bit disorganized, maybe we need a designer to do some designs first

np, will do it

**Comment by BlankParticle** [comment]
😅 Sorry to bother but, You will need to rebase the PR against main branch as we have separated the backend in #109.

**Comment by McPizza0** [comment]
due to changes in security code
and changes to overall codebase

closing this in favor of #208

**Pull request closed without merging**
