### PR TITLE
chore: add script for email stress test

### PR DESCRIPTION
**Pull request by ashgansh**
added scripts to test email sending.

it uses our internal endpoint to send emails to an arbitrary email.

you can use it like this:

```sh
pnpm stress:email email=some@**gmail**.com amount=100 [interval=60] [mode=individual|reply-chain]
```
(more info in readme)

decided to duplicate some code, importing was causing some issue.

since it's not critical part of the app and i think we should get it in.

### CODE REVIEW

**Review by McPizza0 — COMMENTED** [review]
@ashgansh this has merge conflicts
do you wanna check and update this or close the PR?

**Comment by BlankParticle** [comment]
> @ashgansh this has merge conflicts do you wanna check and update this or close the PR?

I will update and merge this PR

**Comment by BlankParticle** [comment]
* **#705** <a href="https://app.graphite.dev/github/pr/un/inbox/705?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ashgansh and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by BlankParticle** [comment]
I have changed the script to be a part of mail bridge as it tests mail bridge, also it uses clack prompts now which is easier/simpler to use.

**Review by BlankParticle — APPROVED** [review]

**Comment by McPizza0** [comment]
### Merge activity

* **Aug 31, 4:10 AM EDT**: @McPizza0 merged this pull request with [Graphite](https://app.graphite.dev/github/pr/un/inbox/705).

**Pull request merged**
