### PR TITLE
select z index fix and input box default length fix

### LINKED ISSUE #568: dialog z-index issue
the z-index of dialog component was set to something super high
this breaks all dropdowns within
CleanShot 2024-07-15 at 15 45 31@2x

### PR DESCRIPTION
**Pull request by yash-kh**
## What does this PR do?

Select z-index fix, model z-index is 500, so I changed the select to have 550.
Team Name Input box default length fix was changing with validation error change fixed.

Fixes #568 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by BlankParticle** [comment]
The issue is not on that specific select box, it is a issue for all select boxes.

@McPizza0, I think we might want to have a list of z-indexes to decide which component should display over which

**Comment by McPizza0** [comment]
@yash-kh i think its better to fix the z-index of the dialog, otherwise we will always keep finding other broken stuff and setting them to z-10000000

maybe the dialog does not even need a z-index 🤔
check how they do it in shadcn and apply

@BlankParticle do you remember why you set the z to 500?

**Comment by BlankParticle** [comment]
> @yash-kh i think its better to fix the z-index of the dialog, otherwise we will always keep finding other broken stuff and setting them to z-10000000
> 
> maybe the dialog does not even need a z-index 🤔 check how they do it in shadcn and apply
> 
> @BlankParticle do you remember why you set the z to 500?

yeah, Portals should take care of z-index unless you are manually adding z-indexes,
I added it in dialogs as you added z-index in the sidebar which broke some dialogs

**Comment by yash-kh** [comment]
> > @yash-kh i think its better to fix the z-index of the dialog, otherwise we will always keep finding other broken stuff and setting them to z-10000000
> > maybe the dialog does not even need a z-index 🤔 check how they do it in shadcn and apply
> > @BlankParticle do you remember why you set the z to 500?
> 
> yeah, Portals should take care of z-index unless you are manually adding z-indexes, I added it in dialogs as you added z-index in the sidebar which broke some dialogs.
> 
> What we can do is keep the default z-index as 100 for all shadcn-components which need z-index and use index<10 for our own stuff like sidebars. so we will have a layer of seperation to work with

Ok, will look into it and try to minimize all the uses of z-index.

**Comment by BlankParticle** [comment]
image
there was this overlap on the sidebar, fixed it by making both the sidebar and button being on z-index: 1

**Review by BlankParticle — APPROVED** [review]

**Pull request merged**
