### PR TITLE
fix: password auto complete suggestion fix

### LINKED ISSUE #461: can't use suggest password
password fields don't accept autosuggestions

### PR DESCRIPTION
**Pull request by yash-kh**
## What does this PR do?
Show password button fix, input uncontrolled state fix, suggestion autofill fix

Fixes #461 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [x] Read [Contributing Guide](https://github.com/un/inbox/blob/main/CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [x] Tested my code in a local environment
- [x] Commented on my code in hard-to-understand areas
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [x] Updated the UnInbox Docs if changes were necessary

Show password button fix:
Before:
Screenshot 2024-07-07 at 2 48 27 PM

After:
Screenshot 2024-07-07 at 2 48 54 PM

input uncontrolled state fix, suggestion autofill fix:
Before:
https://github.com/un/inbox/assets/60394241/d6ae9363-632e-4115-a6c7-3e896bdbd0ad

After:
https://github.com/un/inbox/assets/60394241/68a551cd-e079-4f69-a0f5-694fdbeeb0f7

### CODE REVIEW

**Comment by yash-kh** [comment]
@McPizza0 Made my first contribution, please check it out.

**Review by McPizza0 — APPROVED** [review]

**Comment by McPizza0** [comment]
hey @yash-kh 
great work
can you sign the CLA as per this comment here: https://github.com/un/inbox/pull/546#issuecomment-2212388788

**Review by McPizza0 — CHANGES_REQUESTED** [review]
change to component in https://github.com/un/inbox/issues/548

**Comment by yash-kh** [comment]
@McPizza0 Check out this UI now:
image

**Review by BlankParticle — APPROVED** [review]
tested, works fine

**Comment by McPizza0** [comment]
@yash-kh looks good, can you rename the component to `PasswordInput` as its a more common naming convention

**Review by McPizza0 — APPROVED** [review]

**Comment by McPizza0** [comment]
### Merge activity

* **Jul 8, 9:34 AM EDT**: [Graphite](https://app.graphite.dev/github/pr/un/inbox/546) couldn't merge this PR because it failed for an unknown reason (Stack merges are not currently supported for forked repositories. Please create a branch in the target repository in order to merge).

**Pull request merged**
