### PR TITLE
feat(web): implement `lastLoginAt` to track user last login time

### LINKED ISSUE #94: security(web): add lastLoginAt
we should save the last time a user has logged in to the database
this could be done when we create a session for the user

the data would be used to check for active/inactive users by combining `lastLoginAt` with a check on active sessions

### PR DESCRIPTION
**Pull request by babblebey**
## What does this PR do?

This Pull Request Implements a `lastLoginAt` datetime tracker which tracks the last time a user logged in to the uninbox account.

**Changes Made:**

- Added new field `lastLoginAt` to the `users` table in the `database/schema`
- Implemented logic to update the `"users".lastLogin` for respective user in the following routers for stated actions
  - `signupRouter` - Update `lastLoginAt` field after successfully signing up
  - `passkeyRouter` - Update `lastLoginAt` field after successfully logging in with Passkey
  - `passwordRouter` - Update `lastLoginAt` filed after sucessfulling logging in with Password
  
  Code Implementation

  ```js
  await db.update(users)
      .set({ lastLoginAt: new Date() })
      .where(eq(users.id, userIdValue));
  ```

**Screencasts**

_Logging in User with Password Demo_

[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2024.02.28-08_02_49.webm](https://github.com/un/inbox/assets/25631971/be6ac40c-1f7d-42e6-bfed-a1726ac46f2c)

_Signing Up New User and Logging in User with Passkey Demo_

[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2024.02.28-08_07_15.webm](https://github.com/un/inbox/assets/25631971/d68668c5-b33a-4589-8130-108563283a83)

## Related Issue

Fixes #94

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] Enhancement (small improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Required
- [x] Read [Contributing Guide](https://github.com/un/inbox/blob/main/CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [x] Tested my code in a local environment
- [x] Commented on my code in hard-to-understand areas
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [x] Updated the UnInbox Docs if changes were necessary

### CODE REVIEW

**Review by McPizza0 — CHANGES_REQUESTED** [review]
Great implementation 👏!
can we remove the db migrations stuff, we'll only start using it once we release v0.1 and I want to keep it cleaner for now

**Comment by babblebey** [comment]
> ...can we remove the db migrations stuff, we'll only start using it once we release v0.1 and I want to keep it cleaner for now

Fine thought 😉, should help avoid migration hell haha 😃, I should write down ✍️

**Review by McPizza0 — APPROVED** [review]
lgtm (looks good to me)

**Comment by McPizza0** [comment]
hey @babblebey 

we have been strongly advised to add a contributor license agreement
motivation is to ensure that your contributions can only be "commercialized" or offered as a saas by the UnInbox team (Unproprietary Corporation) and not by others
please head over to https://cla-assistant.io/un/inbox and sign the agreement 
once we have more funds for legal stuff, we'll get a custom one built to add in clauses to the effect of "no changing to non-open licenses" etc.

thank you

**Pull request merged**
