### PR TITLE
fix(landing): OG Images and font issues

### LINKED ISSUE #102: bug(landing-page): Encountering 500 Error on oss-friends Page
When attempting to navigate to the oss-friends page, I  encounter a 500 internal server error.

### PR DESCRIPTION
**Pull request by BlankParticle**
## What does this PR do?

Fixes #102

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Chore (refactoring code, technical debt, workflow improvements)
- [ ] Enhancement (small improvements)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

Fixes the issue with OG images in all pages

Also removes `@nuxtjs/google-fonts` and Inter as it's not being used. Also adds Cal Sans as dependency for proper font loading.

### Required

- [x] Read [Contributing Guide](https://github.com/un/inbox/blob/main/CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [x] Tested my code in a local environment
- [ ] Commented on my code in hard-to-understand areas
- [ ] Checked for warnings, there are none
- [ ] Removed all `console.logs`
- [ ] Merged the latest changes from main onto my branch with `git pull origin main`
- [ ] My changes don't cause any responsiveness issues

### Appreciated

- [ ] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the UnInbox Docs if changes were necessary

### CODE REVIEW

**Comment by BlankParticle** [comment]
Inter was just there but not used anywhere in the project. If you want I can setup Inter propely

**Comment by McPizza0** [comment]
Inter and Cal Sans were set up in tailwind and being used correctly
```
extend: {
      fontFamily: {
        body: ['Inter var', ...defaultTheme.fontFamily.sans],
        display: ['CalSans', ...defaultTheme.fontFamily.sans]
      }
    }
```

^^this combined with the main.css file that points to the font files was working correctly

**Comment by McPizza0** [comment]
the npm method for CalSans is maybe better if not using tailwind... didnt look too much into it

**Comment by BlankParticle** [comment]
> Inter and Cal Sans were set up in tailwind and being used correctly
> 
> ```
> extend: {
>       fontFamily: {
>         body: ['Inter var', ...defaultTheme.fontFamily.sans],
>         display: ['CalSans', ...defaultTheme.fontFamily.sans]
>       }
>     }
> ```
> 
> ^^this combined with the main.css file that points to the font files was working correctly

`font-body` means nothing but a name for the class, In order to use it you need to add the class to the parent elements.
Another way is to call it `sans` which gets auto applied.

Also It's better to use font npm packages, nuxt's google font module increases dev server start up by significant amount

**Comment by BlankParticle** [comment]
I will re-add Inter properly in next commit.

**Comment by McPizza0** [comment]
@BlankParticle are we waiting on anything or is this good to go?

**Comment by BlankParticle** [comment]
no its good to go

**Review by McPizza0 — APPROVED** [review]
lgtm

**Pull request merged**
