### PR TITLE
Add desktop application

### LINKED ISSUE #77: Desktop Application
There appears to be demand for a desktop app.
https://discord.com/channels/1113119653246545961/1207658838925385770

I propose we use Tauri to begin with. It's lighter than Electron, allows us to reuse our existing web-app frontend, and can support localhost if needed for self-hosting via [their 1st-party localhost plugin for production use.](https://github.com/tauri-apps/plugins-workspace/tree/v1/plugins/localhost) 

Tauri will allow us to iterate on top of our existing web app while providing more stable data access interfaces (via their rust bindings to sql) and because it's cross-platform, allows us to bring an enhanced desktop experience very quickly to all desktop users.

There is an option for mobile builds, but that is still in beta. imo, it would be better for us to design a separate mobile application optimised for that platform, rather than deriving off of the web-app's mobile layout.

### PR DESCRIPTION
**Pull request by ezra-en**
🖤
## What does this PR do?

Adds a Tauri desktop app to the monorepo.

Fixes #77 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Chore (refactoring code, technical debt, workflow improvements)
- [x] Enhancement (small improvements)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

### Required
- [x] Read [Contributing Guide](./CONTRIBUTING.md)
- [x] Self-reviewed my own code
- [x] Tested my code in a local environment
- [x] Commented on my code in hard-to-understand areas
- [x] Checked for warnings, there are none
- [x] Removed all `console.logs`
- [x] Merged the latest changes from main onto my branch with `git pull origin main`
- [x] My changes don't cause any responsiveness issues

### Appreciated
Screenshot 2024-02-16 at 3 37 32 AM

- [x] If a UI change was made: Added a screen recording or screenshots to this PR
- [ ] Updated the UnInbox Docs if changes were necessary

### CODE REVIEW

**Comment by ezra-en** [comment]
Huh, not sure why the old commit (`desktop`) is here. I split up the changes earlier, but I guess they disappeared? Let me know if you'd like them broken up again.

**Comment by McPizza0** [comment]
seems like webauthn has some challenges:
https://github.com/tauri-apps/tauri/discussions/6601

**Comment by ezra-en** [comment]
> seems like webauthn has some challenges: [tauri-apps/tauri#6601](https://github.com/tauri-apps/tauri/discussions/6601)
yeah, I think that's what I was encountering earlier [here](https://discord.com/channels/1113119653246545961/1186608361093988392/1207744928868999238). I'd like to wait until #79 goes through before integrating the Tauri API into the web app. 

> there seems to be an authenticator plugin, but we need to check if it would be compatible with passkeys: https://github.com/tauri-apps/plugins-workspace/tree/v1/plugins/authenticator

The idea is to leave your passkey code untouched if Tauri isn't detected, but hook into the Tauri Auth plugin when it is, which might allow us to bypass Webauthn and its impl inconsistencies entirely, but I can't confirm that for sure without checking the source myself (due to a lack of detailed documentation.)

**Comment by McPizza0** [comment]
Yup, looking a bit deeper, so long as the format of the returned security credentials are the same, it shouldnt be an issue

worst case scenario, we implement "login via browser" or "login via another device"

**Comment by ezra-en** [comment]
Sounds good to me!

**Comment by McPizza0** [comment]
lets test once #79 is merged

otherwise we cant do anything in the desktop app due to no password auth

**Comment by ezra-en** [comment]
> @ezra-en did you manage to test with the password auth?

Yes, but a few other issues popped up (those TRPC issues I mentioned before) and I haven't taken the time to test since. Pulled today because I wanted to test again.

**Comment by McPizza0** [comment]
closing in favor of PWA desktop app initially
we can circle back to this in a while

**Pull request closed without merging**
